Feat: 신규 그룹 생성 기능
Princess-in-silvertown/toyou-server pull request #24
Opened 2024-07-12 07:09 UTC by loveysuby

## 🚀 Related Issue

close #23 

## 📌 Tasks

- 새로운 그룹을 생성하는 기능을 추가하였습니다.

## 📝 Details
- 아래 endpoint로 접근 가능합니다.
 
```markdown
// request
// `POST` | /groups/create (name 필드를 requestBody에 동봉합니다.)
{
    "name" : "hart-group"
}

//response
{
      "timestamp": "2024.07.12 16:02:07",
      "code": "TYU-200",
      "message": "응답 성공",
      "data": {
          "id": 1,
          "name": "hart-group"
      }
}
```

## 📚 Remarks

> Points or opinions to share teams

- `users`, `groups` 등등을 단수형으로 표시하도록 수정하는 것이 명확해 보이는데 어떻게 생각하실까요 ? 
  - 단일 엔티티를 복수 개 원하는 api에서의 표현이 불명확해질 것 같다는 생각이 들어서요  🤔 
-

2024-07-12 13:02 UTC, woosung1223 requested changes

2024-07-12 13:02 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
> +				.orElseThrow(() -> new ToyouException(ErrorType.INVALID_GROUP_DATA));
혹시 map 사용하시려고 Optional.of로 감싸셨습니까!

Optional은 null-safe한 코드를 작성하기 위해 사용하는 것입니다.
> A container object which may or may not contain a non-null value. 

map을 Optional에서 정적 함수로 제공하는 이유도 비슷한데, null의 가능성이 있는 객체를 직접적으로 다루지 않고도 타입을 변환시킬 수 있기 때문입니다.

라이브러리를 사용할 땐 (자바 표준 라이브러리도 마찬가지) 설계자의 의도를 지키는게 중요합니다.

2024-07-12 13:02 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
> +	INVALID_GROUP_DATA(HttpStatus.BAD_REQUEST, "TYU-4001", "Invalid group data provided"),
왜 요기만 메세지가 영어인가요?

2024-07-12 13:02 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
> +	@PostMapping("/groups/create")
엔드포인트가 저희 API 명세와 다른 것 같은데요!?!?!

2024-07-12 14:04 UTC, loveysuby reviewed
하하 create는 애초에 errorCode를 따로 만들지 않아도 표준 에러로 명시해줄 수 있을 것 같습니다.

반영해서 수정하겠습니다 !

2024-07-12 14:04 UTC, loveysuby commented on src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
> +				.orElseThrow(() -> new ToyouException(ErrorType.INVALID_GROUP_DATA));
하마터면 엔티티에 명시된 생성자로 가져온 객체인데 불필요한 로직이 들어갈 뻔 했네요 ! 역시 .. 예리하게 짚어주셔서 바로 수정했습니다.

2024-07-12 14:04 UTC, loveysuby commented on src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
> +	@PostMapping("/groups/create")
애초에 그룹 생성에 대한 명세가 없어서 추가하고 그룹 가입과 별개로 두었는데 빠뜨린 부분 있으면 수정하겠습니다 🙀

2024-07-12 14:04 UTC, loveysuby commented on src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
> +	INVALID_GROUP_DATA(HttpStatus.BAD_REQUEST, "TYU-4001", "Invalid group data provided"),
Sorry for mistake. 🧑‍🔬

2024-07-13 08:56 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
> +	@PostMapping("/groups/create")
오 이야기했던 기억은 있는 것 같은데 따로 문서화하진 않았었군요.. 알겠읍니다

다만 API 엔드포인트에 동사는 지양하도록 설계해주세요! 
그룹 생성이라면 `/groups`에 POST 요청을 날리는게 RESTful한 접근 방식입니다.

2024-07-13 08:57 UTC, merged