⚡ Feat : Define common api response
Princess-in-silvertown/toyou-server pull request #9
Opened 2024-07-01 10:37 UTC by loveysuby

## 🚀 Related Issue

close: #6 

## 📌 Tasks

- 공통적으로 사용되는 API 응답 형식을 정의했습니다. 

## 📝 Details

- `PageInfoResponse`를 별도 분리해서 페이징 응답 관련 정보가 공통 응답의 하위 필드로 추가됩니다.
```java
@Getter
@JsonPropertyOrder({"code", "message", "data", "pageInfo"})
public class ApiResponse<T> {

	private final String code;

	private final String message;

	@JsonInclude(Include.NON_NULL)
	private final T data;

	private final PageInfoResponse pageInfo;
```

## 📚 Remarks

> Points or opinions to share teams

- Nullable response인 PageInfoResponse가 있어`Lombok` 으로 생성자 지정하지 않았는데 이에 따른 문제가 있다면 수정해야 합니다.

2024-07-01 12:08 UTC, woosung1223 requested changes
@loveysuby 

깔끔하게 잘 구현해주셨네요 역시 제 수제자입니다. 😎

다만 몇 가지 제안드리고 싶은 부분이 있습니다!

1. 커밋, PR 컨벤션에 관해

저는 개인적으로 복잡한 기능을 쉽게 표현하기 위해 한국어로 커밋 메세지, PR 제목 및 본문을 작성하는 편입니다.
오픈소스화를 고려한다면 영어도 괜찮긴 한데, 한국어로 하는 건 어떠신지.. 여쭤보고 싶습니다. (영어를 잘 못해서;)

Gitmoji도 혹시 정해놓은 컨벤션이 있으실까요? (어떤 상황에 어떤 이모티콘을 쓴다 등)

2. 해당 PR 내용에 관해

잘 구현해주셨는데, 컨트롤러에서 사용할 때에는 형식이 어떻게 되나요?
저도 이런 예외처리 응답 형식을 고려하지 않은 건 아닌데 ResponseEntity와 함께 사용하다보니
`ResponseEntity<ApiResponse<UserResponse>>` 처럼 보기 이쁘지가 않더라고여..

고민하다가 잘 떠오르지 않아서 넘어갔는데 혹시 좋은 아이디어 있으시면 추천해주시면 감사하겠습니다..
이건 수정 요청이 아니라 반영 여부에 상관없이 머지는 할 예정입니다!

2024-07-01 12:08 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/common/ApiResponse.java
> +	}
생성자 체이닝으로 두면 깔끔할 것 같습니다!

2024-07-01 12:08 UTC, woosung1223 commented on src/main/java/slvtwn/khu/toyouserver/common/ApiResponse.java
> +	public static <T> ApiResponse<T> error(ErrorType errorType, String message, T data) {
여기도요!

2024-07-01 23:08 UTC, merged

2024-07-05 16:18 UTC, loveysuby reviewed
@woosung1223 

이후에 바꾸기 어려운 부분이라 조금 더 신경써서 수정해봤습니다. 🙀

`ApiResponse`에서는 성공 및 예외 응답을 모두 담을 수 있어야 하고, 이는 응답 body를 공동으로 advice에서 처리하도록 바꿨습니다. 

`ApiResponseAdvice`에서는 end-point는 맞지만 요청 형식이 잘 못 되었을 때 `createResponseByHttpStatus`에서 분기하도록 작성했는데, 이게 필요할지는 잘 모르겠습니다 🤔

응답 객체 사용 예시를 테스트로 같이 넣어봤는데, 코드가 실효성이 부족해 보여서 확인 부탁드립니다.

2024-07-05 16:18 UTC, loveysuby commented on src/main/java/slvtwn/khu/toyouserver/common/ApiResponse.java
> +	public static <T> ApiResponse<T> error(ErrorType errorType, String message, T data) {
`success`, `error` 케이스가 너무 난잡하기도 하고, 응답 처리를 `ApiResponseAdvice`에서 일괄 처리하도록 바꿔봤습니다. 🤔

2024-07-05 16:18 UTC, loveysuby commented on src/main/java/slvtwn/khu/toyouserver/common/PageInfoResponse.java
> +	public static PageInfoResponse of(int currentPage, int totalPage, int totalElements) {
모든 요청이 paging이 들어가지는 않아서, `PageInfoResponse`를 공통 응답에 필드로 두는 것보다 data의 하위로 두고 필요할 때만 `PageInfoResponse` 등으로 담아서 주는 방식도 괜찮은 것 같아 수정했습니다.

응답 형식은 아래와 같이 전달됩니다. 어떠실까요 ? 🤔
```json
{
    "timestamp": "2024.07.06 00:35:58",
    "code": "TYU-200",
    "message": "응답 성공",
    "data": {
        "id": 1,
        "name": "health",
        "pageInfo": {
            "currentPage": 1,
            "totalPage": 1,
            "totalElements": 1
        }
    }
}
```